trigger:
- master

pool:
  name: 'Default'

variables:
  solution: 'MvcMovie.sln'  # Adjust path if the .sln file is in a subfolder
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
# Install NuGet Tool
- task: NuGetToolInstaller@1

# Install .NET Core SDK
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: '8.x'  # Use the appropriate .NET SDK version
    installationPath: 'C:\sdk'

# Debug Directory Contents
- script: |
    echo "Debugging working directory contents..."
    dir $(System.DefaultWorkingDirectory)
  displayName: "Debug Working Directory"

# Restore Dependencies
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

# Build Solution
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# Run Tests
- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
