trigger:
- master

pool:
  name: 'Default'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
# Install NuGet Tool
- task: NuGetToolInstaller@1

# Restore Dependencies
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

# Debug Restore Outputs
- script: |
    echo "Debugging restore outputs..."
    dir $(Agent.BuildDirectory)
  displayName: "Debug Restore Outputs"

# Clean Build Directory
- script: |
    echo "Cleaning up old build artifacts..."
    rd /s /q "$(Agent.BuildDirectory)"
  displayName: "Clean Build Directory"

# Build Solution
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# Run Tests
- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
